# Generated by Django 4.1.7 on 2023-02-23 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='best_month_to_visit',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='num_of_days_to_visit',
            new_name='month',
        ),
    ]
