# Generated by Django 4.1.7 on 2023-02-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_best_month_to_visit_countries_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='days',
        ),
    ]
