# Generated by Django 4.1.7 on 2023-02-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_remove_countries_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
